// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "180723_milestone-122-g2079cc9-dirty"
#define MICROPY_GIT_HASH "2079cc9-dirty"
#define MICROPY_BUILD_DATE "2020-05-08"

#define OPENMV_GIT_TAG "0.12-70-g53e08e6-dirty"
#define OPENMV_GIT_HASH "53e08e6-dirty"
#define MICROPY_BUILD_DATE "2020-02-26"