// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.18"
#define MICROPY_GIT_HASH "2079cc9-dirty"
#define MICROPY_BUILD_DATE "2020-05-08"

#define OPENMV_GIT_TAG "0.13.0"
#define OPENMV_GIT_HASH "53e08e6-dirty"
#define MICROPY_BUILD_DATE "2022-08-10"